name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          maven-version: '3.8.4'

      - name: Build with Maven
        run: mvn clean install -DskipTests
