name: Deploy to Heroku
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          maven-version: '3.8.4'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: task-management-api-test
          heroku_email: connor.d.burge@gmail.com
          env_vars: |
            DATABASE_URL=${{ secrets.DB_URL }}
            DATABASE_USERNAME=${{ secrets.DB_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}
