name: Update README

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run update_readme.py script
        run: |
          python .github/update_readme.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update endpoints in README"
          
      - name: Force push changes
        run: |
          export GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}
          git push --force origin HEAD:main
